apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: apimong
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: localhost:5000/api:1
          ports:
            - containerPort: 3002
