apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmongo
  namespace: dbmongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmongo
  template:
    metadata:
      labels:
        app: cmongo
    spec:
      containers:
        - name: cmongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: cmongo