apiVersion: v1
kind: Service
metadata:
    name: api
    namespace: apimong
spec:
    selector:
        app: api
    ports:
        - protocol: TCP
          port: 3002
          targetPort: 3002
